const $ = (selector) => document.querySelector(selector);
let data;
let invoices = [];
let activeInvoicePath = null;
let dashboardOpening = {};
const currency = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' });
const installed = window.matchMedia('(display-mode: standalone)').matches || window.navigator.standalone === true;
let toastTimer;
function notify(message, type = 'success') { const toast = $('#toast'); toast.textContent = message; toast.className = `pointer-events-none fixed inset-x-4 bottom-5 z-50 mx-auto max-w-sm rounded-xl px-4 py-3 text-sm font-semibold text-white shadow-xl ${type === 'success' ? 'bg-teal-700' : 'bg-red-700'}`; clearTimeout(toastTimer); toastTimer = setTimeout(() => toast.classList.add('hidden'), 3200); }
async function withLoading(button, label, task) { if (button.disabled) return; const original = button.innerHTML; button.disabled = true; button.classList.add('cursor-wait', 'opacity-75'); button.innerHTML = `<span class="mr-2 inline-block h-3.5 w-3.5 animate-spin rounded-full border-2 border-current border-r-transparent align-[-2px]"></span>${label}`; try { await task(); } catch (error) { notify(error.message || 'Something went wrong.', 'error'); } finally { button.disabled = false; button.classList.remove('cursor-wait', 'opacity-75'); button.innerHTML = original; } }
const dbPromise = new Promise((resolve, reject) => { const request = indexedDB.open('invoice-simple-secure', 1); request.onupgradeneeded = () => request.result.createObjectStore('settings'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
async function getSecureSetting(key) { const db = await dbPromise; return new Promise((resolve, reject) => { const request = db.transaction('settings').objectStore('settings').get(key); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function setSecureSetting(key, value) { const db = await dbPromise; return new Promise((resolve, reject) => { const request = db.transaction('settings', 'readwrite').objectStore('settings').put(value, key); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error); }); }
async function cryptoKey() { let key = await getSecureSetting('crypto-key'); if (!key) { key = await crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']); await setSecureSetting('crypto-key', key); } return key; }
async function saveToken(token) { const iv = crypto.getRandomValues(new Uint8Array(12)); const encrypted = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, await cryptoKey(), new TextEncoder().encode(token)); await setSecureSetting('github-token', { iv: [...iv], encrypted }); }
async function readToken() { const stored = await getSecureSetting('github-token'); if (!stored) return ''; const decrypted = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: new Uint8Array(stored.iv) }, await cryptoKey(), stored.encrypted); return new TextDecoder().decode(decrypted); }

async function loadData() {
  const saved = localStorage.getItem('invoice-simple-data');
  if (installed && await hasConnection()) { try { data = await getRemoteData(); } catch { data = await fetch('data.json').then((r) => r.json()); } } else data = saved ? JSON.parse(saved) : await fetch('data.json').then((r) => r.json());
  renderLists(); renderDatalists(); applyBranding();
}
async function getRemoteData() { const repo = await getSecureSetting('github-repo'), branch = await getSecureSetting('github-branch'), token = await readToken(); const response = await fetch(`https://api.github.com/repos/${repo}/contents/data.json?ref=${encodeURIComponent(branch)}`, { headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' } }); if (response.status === 404) throw new Error('The data source has no data.json yet.'); if (!response.ok) throw new Error('Could not load the configured data source.'); return JSON.parse(decodeURIComponent(escape(atob((await response.json()).content.replace(/\n/g, ''))))); }
function saveData() { localStorage.setItem('invoice-simple-data', JSON.stringify(data)); renderLists(); renderDatalists(); applyBranding(); }
async function applyBranding() { const invoiceLogo = data.invoiceLogoPath || data.logoPath; const appLogo = data.appLogoPath || invoiceLogo; for (const [path, id] of [[appLogo, 'logoImage'], [invoiceLogo, 'invoiceLogoImage'], [data.qrPath, 'qrImage']]) { const image = $(`#${id}`); const exists = Boolean(path); image.classList.toggle('hidden', !exists); if (exists) image.src = await assetUrl(path); } $('#logoFallback').classList.toggle('hidden', Boolean(appLogo)); }
async function assetUrl(path) { if (!installed || !(await hasConnection())) return new URL(path, location.href).href; const repo = await getSecureSetting('github-repo'), branch = await getSecureSetting('github-branch'), token = await readToken(); const response = await fetch(`https://api.github.com/repos/${repo}/contents/${path}?ref=${encodeURIComponent(branch)}`, { headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' } }); if (!response.ok) return ''; const file = await response.json(); return `data:${file.type || 'image/png'};base64,${file.content.replace(/\n/g, '')}`; }
function renderDatalists() {
  $('#parties').innerHTML = data.parties.map((party) => `<option value="${escapeHtml(party)}">`).join('');
  document.querySelectorAll('#items').forEach((list) => list.innerHTML = data.items.map((item) => `<option value="${escapeHtml(item.name)}">`).join(''));
}
function renderLists() {
  $('#partyList').innerHTML = data.parties.map((party, i) => `<li class="flex items-center justify-between gap-2 py-2 text-sm"><span>${escapeHtml(party)}</span><span class="shrink-0 space-x-2"><button data-edit-party="${i}" class="font-semibold text-teal-700">Edit</button><button data-party="${i}" class="remove-party text-red-600">Remove</button></span></li>`).join('');
  $('#itemList').innerHTML = data.items.map((item, i) => `<li class="flex items-center justify-between gap-2 py-2 text-sm"><span>${escapeHtml(item.name)} <span class="text-slate-500">${currency.format(item.rate)}</span></span><span class="shrink-0 space-x-2"><button data-edit-item="${i}" class="font-semibold text-teal-700">Edit</button><button data-item="${i}" class="remove-item text-red-600">Remove</button></span></li>`).join('');
}
function escapeHtml(value) { const el = document.createElement('div'); el.textContent = value; return el.innerHTML; }
function addLine(item = {}) {
  const row = $('#lineTemplate').content.cloneNode(true);
  row.querySelector('.item-name').value = item.name || ''; row.querySelector('.quantity').value = item.quantity || 1; row.querySelector('.rate').value = item.rate || '';
  $('#lineItems').append(row); renderDatalists(); updateTotals();
}
function updateTotals() {
  let total = 0; document.querySelectorAll('#lineItems tr').forEach((row) => { const amount = (+row.querySelector('.quantity').value || 0) * (+row.querySelector('.rate').value || 0); row.querySelector('.amount').textContent = currency.format(amount); total += amount; });
  $('#subtotal').textContent = currency.format(total); $('#grandTotal').textContent = currency.format(total);
}
function setView(view) { if (view === 'settings' && !installed) return; $('#invoiceView').classList.toggle('hidden', view !== 'invoice'); $('#settingsView').classList.toggle('hidden', view !== 'settings'); $('#dashboardView').classList.toggle('hidden', view !== 'dashboard'); if (view === 'dashboard') loadDashboard(); }
function setSettingsCategory(category) { document.querySelectorAll('.settings-panel').forEach((panel) => panel.classList.toggle('hidden', panel.dataset.category !== category)); document.querySelectorAll('.settings-nav-card').forEach((button) => button.setAttribute('aria-pressed', button.dataset.category === category)); }
async function hasConnection() { return Boolean(await getSecureSetting('github-repo') && await getSecureSetting('github-branch') && await getSecureSetting('github-token')); }
async function requireConnection() { if (await hasConnection()) return true; alert('Set up and save the Data connection first.'); $('#dataSettings').scrollIntoView({ behavior: 'smooth', block: 'start' }); return false; }
async function saveConnection() { const repo = $('#githubRepo').value.trim(), enteredBranch = $('#githubBranch').value.trim(), enteredToken = $('#githubToken').value.trim(), status = $('#connectionStatus'), previousRepo = await getSecureSetting('github-repo'), previousBranch = await getSecureSetting('github-branch'), token = enteredToken || await readToken(); if (!/^[^/]+\/[^/]+$/.test(repo) || !enteredBranch || !token) { status.textContent = 'Enter a valid repository, branch, and token.'; status.className = 'mt-3 text-sm text-red-700'; return; } if (previousRepo && (previousRepo !== repo || previousBranch !== enteredBranch) && !confirm('Changing the data source can replace the parties, items, logo, and QR currently shown in this app. Continue?')) return; status.textContent = 'Checking data source…'; const headers = { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' }; let source = await fetch(`https://api.github.com/repos/${repo}`, { headers }); if (source.status === 404) { const [owner, name] = repo.split('/'); const user = await fetch('https://api.github.com/user', { headers }); if (!user.ok) { status.textContent = 'Your token could not be verified.'; return; } const account = await user.json(); let canCreate = account.login.toLowerCase() === owner.toLowerCase(); if (!canCreate) { const membership = await fetch(`https://api.github.com/user/memberships/orgs/${owner}`, { headers }); canCreate = membership.ok && (await membership.json()).state === 'active'; } if (!canCreate) { status.textContent = 'This token does not appear to have permission to create a repository for that owner.'; status.className = 'mt-3 text-sm text-red-700'; return; } if (!confirm(`Repository ${repo} does not exist. Create it as a private data repository?`)) return; const endpoint = account.login.toLowerCase() === owner.toLowerCase() ? 'https://api.github.com/user/repos' : `https://api.github.com/orgs/${owner}/repos`; source = await fetch(endpoint, { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ name, private: true, auto_init: true }) }); if (!source.ok) { status.textContent = (await source.json()).message || 'Repository creation was denied.'; status.className = 'mt-3 text-sm text-red-700'; return; } const created = await source.json(); $('#githubBranch').value = created.default_branch; } else if (!source.ok) { status.textContent = 'Could not access that repository.'; status.className = 'mt-3 text-sm text-red-700'; return; } const branch = $('#githubBranch').value.trim(); await setSecureSetting('github-repo', repo); await setSecureSetting('github-branch', branch); if (enteredToken) await saveToken(enteredToken); $('#githubToken').value = ''; $('#tokenHint').textContent = 'A token is saved. Enter a new one only to replace it.'; status.textContent = 'Data source saved.'; status.className = 'mt-3 text-sm text-green-700'; notify('Data source saved.'); try { await loadData(); } catch {} }

document.addEventListener('click', async (event) => {
  const target = event.target;
  if (target.dataset.view) setView(target.dataset.view);
  if (target.id === 'addLine') addLine();
  if (target.classList.contains('remove-line')) { target.closest('tr').remove(); updateTotals(); }
  if (target.classList.contains('remove-party')) { if (!(await requireConnection())) return; data.parties.splice(+target.dataset.party, 1); saveData(); }
  if (target.classList.contains('remove-item')) { if (!(await requireConnection())) return; data.items.splice(+target.dataset.item, 1); saveData(); }
  if (target.dataset.editParty !== undefined) { if (!(await requireConnection())) return; const index = +target.dataset.editParty, next = prompt('Party name', data.parties[index])?.trim(); if (next && !data.parties.includes(next)) { data.parties[index] = next; data.parties.sort(); saveData(); notify('Party updated.'); } }
  if (target.dataset.editItem !== undefined) { if (!(await requireConnection())) return; const index = +target.dataset.editItem, item = data.items[index], name = prompt('Item name', item.name)?.trim(); if (!name) return; const rate = Number(prompt('Default rate', item.rate)); if (Number.isFinite(rate) && rate >= 0) { data.items[index] = { name, rate }; data.items.sort((a, b) => a.name.localeCompare(b.name)); saveData(); notify('Item updated.'); } }
  if (target.id === 'newInvoice') resetInvoice();
  if (target.id === 'saveInvoice') await withLoading(target, 'Saving…', saveInvoice);
  if (target.dataset.openInvoice) openInvoice(target.dataset.openInvoice);
  if (target.id === 'printInvoice') window.print();
  if (target.id === 'saveConnection') await withLoading(target, 'Saving…', saveConnection);
  if (target.id === 'commitParties' || target.id === 'commitItems') await withLoading(target, 'Saving…', async () => { if (await requireConnection()) await commitData(); });
  if (target.id === 'saveInvoiceLogo') await withLoading(target, 'Saving…', () => uploadAsset('invoiceLogo'));
  if (target.id === 'saveAppLogo') await withLoading(target, 'Saving…', () => uploadAsset('appLogo'));
  if (target.id === 'saveQr') await withLoading(target, 'Saving…', () => uploadAsset('qr'));
});
document.addEventListener('input', (event) => { if (event.target.closest('#lineItems')) updateTotals(); });
document.addEventListener('change', (event) => { if (event.target.classList.contains('item-name')) { const item = data.items.find((x) => x.name === event.target.value); if (item) { event.target.closest('tr').querySelector('.rate').value = item.rate; updateTotals(); } } if (event.target.id === 'paymentStatus') updatePaymentFields(); if (event.target.id === 'dashboardYear') loadDashboard(); });
$('#settingsNav').addEventListener('click', (event) => { const button = event.target.closest('.settings-nav-card'); if (button) setSettingsCategory(button.dataset.category); });
$('#invoiceSearch').addEventListener('input', () => renderDashboard(dashboardOpening));
$('#partyForm').addEventListener('submit', async (event) => { event.preventDefault(); if (!(await requireConnection())) return; const name = $('#newParty').value.trim(); if (name && !data.parties.includes(name)) { data.parties.push(name); data.parties.sort(); saveData(); } event.target.reset(); });
$('#itemForm').addEventListener('submit', async (event) => { event.preventDefault(); if (!(await requireConnection())) return; const name = $('#newItem').value.trim(), rate = +$('#newRate').value; if (name && !data.items.some((x) => x.name === name)) { data.items.push({ name, rate }); data.items.sort((a,b) => a.name.localeCompare(b.name)); saveData(); } event.target.reset(); });
async function commitData() {
  if (!installed) return; const [repo, branch] = [await getSecureSetting('github-repo'), await getSecureSetting('github-branch')]; const status = $('#commitStatus'); const token = await readToken();
  if (!/^[^/]+\/[^/]+$/.test(repo) || !branch || !token) { status.textContent = 'Enter repository, branch, and token.'; status.className = 'mt-3 text-sm text-red-700'; return; }
  status.textContent = 'Committing…'; status.className = 'mt-3 text-sm text-amber-900';
  try { const url = `https://api.github.com/repos/${repo}/contents/data.json`; const headers = { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' }; const current = await fetch(`${url}?ref=${encodeURIComponent(branch)}`, { headers }); if (!current.ok && current.status !== 404) throw new Error('Could not read data.json. Check repository, branch, and token.'); const file = current.ok ? await current.json() : null; const payload = { message: 'Update invoice data', content: btoa(unescape(encodeURIComponent(JSON.stringify(data, null, 2) + '\n'))), ...(file ? { sha: file.sha } : {}), branch }; const response = await fetch(url, { method: 'PUT', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error((await response.json()).message || 'Commit failed.'); status.textContent = 'Saved and committed. Data source will update shortly.'; status.className = 'mt-3 text-sm text-green-700'; notify('Saved successfully.'); } catch (error) { status.textContent = error.message; status.className = 'mt-3 text-sm text-red-700'; }
}
async function uploadAsset(kind) { if (!(await requireConnection())) return; const file = $(`#${kind}File`).files[0], status = $('#commitStatus'); if (!file || !file.type.startsWith('image/') || file.size > 2 * 1024 * 1024) { status.textContent = 'Choose an image under 2 MB.'; status.className = 'mt-3 text-sm text-red-700'; return; } status.textContent = `Uploading ${kind}…`; const repo = await getSecureSetting('github-repo'), branch = await getSecureSetting('github-branch'), token = await readToken(); const ext = ({ 'image/png': 'png', 'image/jpeg': 'jpg', 'image/webp': 'webp', 'image/svg+xml': 'svg' })[file.type] || 'png'; const path = `assets/${kind}.${ext}`, url = `https://api.github.com/repos/${repo}/contents/${path}`, headers = { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' }; try { const current = await fetch(`${url}?ref=${encodeURIComponent(branch)}`, { headers }); const existing = current.ok ? await current.json() : null; if (!current.ok && current.status !== 404) throw new Error('Could not access the asset location.'); const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ''; bytes.forEach((byte) => binary += String.fromCharCode(byte)); const response = await fetch(url, { method: 'PUT', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ message: `Upload invoice ${kind}`, content: btoa(binary), ...(existing ? { sha: existing.sha } : {}), branch }) }); if (!response.ok) throw new Error((await response.json()).message || 'Upload failed.'); data[`${kind}Path`] = path; saveData(); await commitData(); } catch (error) { status.textContent = error.message; status.className = 'mt-3 text-sm text-red-700'; } }
function invoiceTotal() { return [...document.querySelectorAll('#lineItems tr')].reduce((sum, row) => sum + (+row.querySelector('.quantity').value || 0) * (+row.querySelector('.rate').value || 0), 0); }
function paymentValue(invoice) { return invoice.status === 'paid' ? invoice.total : Math.min(+invoice.paidAmount || 0, invoice.total); }
function updatePaymentFields() { const paid = $('#paymentStatus').value === 'paid'; $('#paymentAmountWrap').classList.toggle('hidden', paid || $('#paymentStatus').value === 'unpaid'); $('#paymentDateWrap').classList.toggle('hidden', $('#paymentStatus').value === 'unpaid'); if (paid) $('#paidAmount').value = invoiceTotal(); }
function resetInvoice() { activeInvoicePath = null; $('#invoiceTitle').textContent = 'New invoice'; $('#partyInput').value = ''; $('#notes').value = ''; $('#paymentStatus').value = 'unpaid'; $('#paidAmount').value = '0'; $('#paymentDate').value = ''; $('#invoiceDate').value = new Date().toISOString().slice(0, 10); $('#invoiceNumber').value = `INV-${new Date().getFullYear()}-${String(invoices.length + 1).padStart(3, '0')}`; $('#lineItems').innerHTML = ''; addLine(); updatePaymentFields(); }
async function githubFile(path) { const repo = await getSecureSetting('github-repo'), branch = await getSecureSetting('github-branch'), token = await readToken(); const response = await fetch(`https://api.github.com/repos/${repo}/contents/${path}?ref=${encodeURIComponent(branch)}`, { headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' } }); return response; }
async function invoicesForYear(year) { const directory = await githubFile(`invoices/${year}`); if (directory.status === 404) return []; if (!directory.ok) throw new Error('Could not fetch invoices.'); const files = await directory.json(); return Promise.all(files.filter((file) => file.type === 'file' && file.name.endsWith('.json')).map(async (file) => { const response = await githubFile(file.path); return JSON.parse(decodeURIComponent(escape(atob((await response.json()).content.replace(/\n/g, ''))))); })); }
async function loadDashboard() { if (!installed || !(await requireConnection())) return; const currentYear = String(new Date().getFullYear()); const selected = $('#dashboardYear').value || currentYear; try { invoices = await invoicesForYear(selected); const directory = await githubFile('invoices'); const years = directory.ok ? (await directory.json()).filter((entry) => entry.type === 'dir').map((entry) => entry.name).sort().reverse() : []; if (!years.includes(selected)) years.unshift(selected); $('#dashboardYear').innerHTML = years.map((year) => `<option ${year === selected ? 'selected' : ''}>${year}</option>`).join(''); dashboardOpening = {}; for (const year of years.filter((year) => year < selected)) for (const invoice of await invoicesForYear(year)) dashboardOpening[invoice.party] = (dashboardOpening[invoice.party] || 0) + invoice.total - paymentValue(invoice); renderDashboard(dashboardOpening); } catch (error) { $('#invoiceList').innerHTML = `<tr><td colspan="6" class="py-5 text-center text-red-600">${escapeHtml(error.message)}</td></tr>`; } }
function renderDashboard(opening = {}) { const term = $('#invoiceSearch').value.trim().toLowerCase(); const shown = invoices.filter((invoice) => `${invoice.number} ${invoice.party}`.toLowerCase().includes(term)); const total = invoices.reduce((sum, invoice) => sum + invoice.total, 0), paid = invoices.reduce((sum, invoice) => sum + paymentValue(invoice), 0), outstanding = total - paid; $('#dashboardStats').innerHTML = [["Invoiced", total, 'text-ink'], ["Collected", paid, 'text-teal-700'], ["Outstanding", outstanding, 'text-amber-700']].map(([label, value, color]) => `<div class="rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200"><p class="text-sm text-slate-500">${label}</p><p class="mt-1 text-2xl font-bold ${color}">${currency.format(value)}</p></div>`).join(''); $('#invoiceList').innerHTML = shown.length ? shown.sort((a,b) => b.date.localeCompare(a.date)).map((invoice) => `<tr class="border-b border-slate-100"><td class="py-3 font-semibold">${escapeHtml(invoice.number)}</td><td class="py-3">${escapeHtml(invoice.party)}</td><td class="py-3">${invoice.date}</td><td class="py-3 text-right">${currency.format(invoice.total)}</td><td class="py-3 capitalize">${invoice.status}${invoice.paymentDate ? ` · ${invoice.paymentDate}` : ''}</td><td class="py-3 text-right"><button data-open-invoice="${escapeHtml(invoice.path)}" class="font-semibold text-teal-700">Edit</button></td></tr>`).join('') : '<tr><td colspan="6" class="py-5 text-center text-slate-500">No invoices found.</td></tr>'; const balances = {}; for (const invoice of invoices) { const party = balances[invoice.party] ||= { invoiced: 0, paid: 0 }; party.invoiced += invoice.total; party.paid += paymentValue(invoice); } for (const [party, amount] of Object.entries(opening)) (balances[party] ||= { invoiced: 0, paid: 0 }).opening = amount; $('#partyBalances').innerHTML = Object.entries(balances).map(([party, value]) => { const start = value.opening || 0, due = start + value.invoiced - value.paid; return `<tr class="border-b border-slate-100"><td class="py-3 font-medium">${escapeHtml(party)}</td><td class="py-3 text-right">${currency.format(start)}</td><td class="py-3 text-right">${currency.format(value.invoiced)}</td><td class="py-3 text-right">${currency.format(value.paid)}</td><td class="py-3 text-right font-semibold">${currency.format(due)}</td></tr>`; }).join('') || '<tr><td colspan="5" class="py-5 text-center text-slate-500">No party balances yet.</td></tr>'; }
async function saveInvoice() { if (!(await requireConnection())) return; const number = $('#invoiceNumber').value.trim(), date = $('#invoiceDate').value, party = $('#partyInput').value.trim(), status = $('#paymentStatus').value, total = invoiceTotal(); if (!number || !date || !party || !total) return alert('Add an invoice number, date, party, and at least one priced item.'); const year = date.slice(0, 4), fileName = number.replace(/[^a-z0-9_-]/gi, '-'), path = activeInvoicePath || `invoices/${year}/${fileName}.json`, invoice = { number, date, party, items: [...document.querySelectorAll('#lineItems tr')].map((row) => ({ name: row.querySelector('.item-name').value, quantity: +row.querySelector('.quantity').value, rate: +row.querySelector('.rate').value })), notes: $('#notes').value, total, status, paidAmount: status === 'paid' ? total : +$('#paidAmount').value || 0, paymentDate: status === 'unpaid' ? null : $('#paymentDate').value || null, updatedAt: new Date().toISOString(), path }; const repo = await getSecureSetting('github-repo'), branch = await getSecureSetting('github-branch'), token = await readToken(), url = `https://api.github.com/repos/${repo}/contents/${path}`, headers = { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' }; try { const current = await fetch(`${url}?ref=${encodeURIComponent(branch)}`, { headers }); const existing = current.ok ? await current.json() : null; const response = await fetch(url, { method: 'PUT', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ message: `Save invoice ${number}`, content: btoa(unescape(encodeURIComponent(JSON.stringify(invoice, null, 2) + '\n'))), ...(existing ? { sha: existing.sha } : {}), branch }) }); if (!response.ok) throw new Error((await response.json()).message || 'Could not save invoice.'); activeInvoicePath = path; notify('Invoice saved successfully.'); } catch (error) { notify(error.message, 'error'); } }
function openInvoice(path) { const invoice = invoices.find((entry) => entry.path === path); if (!invoice) return; activeInvoicePath = path; $('#invoiceTitle').textContent = `Invoice ${invoice.number}`; $('#invoiceNumber').value = invoice.number; $('#invoiceDate').value = invoice.date; $('#partyInput').value = invoice.party; $('#notes').value = invoice.notes || ''; $('#paymentStatus').value = invoice.status; $('#paidAmount').value = invoice.paidAmount || 0; $('#paymentDate').value = invoice.paymentDate || ''; $('#lineItems').innerHTML = ''; invoice.items.forEach(addLine); updatePaymentFields(); setView('invoice'); }
let installPrompt;
window.addEventListener('beforeinstallprompt', (event) => { event.preventDefault(); installPrompt = event; $('#installButton').classList.remove('hidden'); });
$('#installButton').addEventListener('click', async () => { if (!installPrompt) return; installPrompt.prompt(); await installPrompt.userChoice; installPrompt = null; $('#installButton').classList.add('hidden'); });
if (installed) { $('#settingsButton').classList.remove('hidden'); $('#dashboardButton').classList.remove('hidden'); }
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
$('#invoiceDate').value = new Date().toISOString().slice(0, 10);
await loadData(); resetInvoice();
$('#settingsPanels').append($('#dataSettings')); setSettingsCategory('parties');
if (installed) { $('#githubRepo').value = await getSecureSetting('github-repo') || ''; $('#githubBranch').value = await getSecureSetting('github-branch') || 'main'; if (await getSecureSetting('github-token')) { $('#tokenHint').textContent = 'A token is saved. Enter a new one only to replace it.'; setView('dashboard'); } else { setView('settings'); setSettingsCategory('data'); alert('Set up a data source before managing parties, items, logo, or QR codes.'); } }
