const $ = (selector) => document.querySelector(selector);
let data;
const currency = new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' });
const installed = window.matchMedia('(display-mode: standalone)').matches || window.navigator.standalone === true;
const dbPromise = new Promise((resolve, reject) => { const request = indexedDB.open('invoice-simple-secure', 1); request.onupgradeneeded = () => request.result.createObjectStore('settings'); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); });
async function getSecureSetting(key) { const db = await dbPromise; return new Promise((resolve, reject) => { const request = db.transaction('settings').objectStore('settings').get(key); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
async function setSecureSetting(key, value) { const db = await dbPromise; return new Promise((resolve, reject) => { const request = db.transaction('settings', 'readwrite').objectStore('settings').put(value, key); request.onsuccess = () => resolve(); request.onerror = () => reject(request.error); }); }
async function cryptoKey() { let key = await getSecureSetting('crypto-key'); if (!key) { key = await crypto.subtle.generateKey({ name: 'AES-GCM', length: 256 }, false, ['encrypt', 'decrypt']); await setSecureSetting('crypto-key', key); } return key; }
async function saveToken(token) { const iv = crypto.getRandomValues(new Uint8Array(12)); const encrypted = await crypto.subtle.encrypt({ name: 'AES-GCM', iv }, await cryptoKey(), new TextEncoder().encode(token)); await setSecureSetting('github-token', { iv: [...iv], encrypted }); }
async function readToken() { const stored = await getSecureSetting('github-token'); if (!stored) return ''; const decrypted = await crypto.subtle.decrypt({ name: 'AES-GCM', iv: new Uint8Array(stored.iv) }, await cryptoKey(), stored.encrypted); return new TextDecoder().decode(decrypted); }

async function loadData() {
  const saved = localStorage.getItem('invoice-simple-data');
  if (installed && await hasConnection()) { try { data = await getRemoteData(); } catch { data = await fetch('data.json').then((r) => r.json()); } } else data = saved ? JSON.parse(saved) : await fetch('data.json').then((r) => r.json());
  renderLists(); renderDatalists(); applyBranding();
}
async function getRemoteData() { const repo = await getSecureSetting('github-repo'), branch = await getSecureSetting('github-branch'), token = await readToken(); const response = await fetch(`https://api.github.com/repos/${repo}/contents/data.json?ref=${encodeURIComponent(branch)}`, { headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' } }); if (response.status === 404) throw new Error('The data source has no data.json yet.'); if (!response.ok) throw new Error('Could not load the configured data source.'); return JSON.parse(decodeURIComponent(escape(atob((await response.json()).content.replace(/\n/g, ''))))); }
function saveData() { localStorage.setItem('invoice-simple-data', JSON.stringify(data)); renderLists(); renderDatalists(); applyBranding(); }
async function applyBranding() { for (const [property, id] of [['logoPath', 'logoImage'], ['qrPath', 'qrImage']]) { const image = $(`#${id}`); const exists = Boolean(data[property]); image.classList.toggle('hidden', !exists); if (exists) image.src = await assetUrl(data[property]); } $('#logoFallback').classList.toggle('hidden', Boolean(data.logoPath)); }
async function assetUrl(path) { if (!installed || !(await hasConnection())) return new URL(path, location.href).href; const repo = await getSecureSetting('github-repo'), branch = await getSecureSetting('github-branch'), token = await readToken(); const response = await fetch(`https://api.github.com/repos/${repo}/contents/${path}?ref=${encodeURIComponent(branch)}`, { headers: { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' } }); if (!response.ok) return ''; const file = await response.json(); return `data:${file.type || 'image/png'};base64,${file.content.replace(/\n/g, '')}`; }
function renderDatalists() {
  $('#parties').innerHTML = data.parties.map((party) => `<option value="${escapeHtml(party)}">`).join('');
  document.querySelectorAll('#items').forEach((list) => list.innerHTML = data.items.map((item) => `<option value="${escapeHtml(item.name)}">`).join(''));
}
function renderLists() {
  $('#partyList').innerHTML = data.parties.map((party, i) => `<li class="flex items-center justify-between py-2 text-sm"><span>${escapeHtml(party)}</span><button data-party="${i}" class="remove-party text-red-600">Remove</button></li>`).join('');
  $('#itemList').innerHTML = data.items.map((item, i) => `<li class="flex items-center justify-between py-2 text-sm"><span>${escapeHtml(item.name)} <span class="text-slate-500">${currency.format(item.rate)}</span></span><button data-item="${i}" class="remove-item text-red-600">Remove</button></li>`).join('');
}
function escapeHtml(value) { const el = document.createElement('div'); el.textContent = value; return el.innerHTML; }
function addLine(item = {}) {
  const row = $('#lineTemplate').content.cloneNode(true);
  row.querySelector('.item-name').value = item.name || ''; row.querySelector('.rate').value = item.rate || '';
  $('#lineItems').append(row); renderDatalists(); updateTotals();
}
function updateTotals() {
  let total = 0; document.querySelectorAll('#lineItems tr').forEach((row) => { const amount = (+row.querySelector('.quantity').value || 0) * (+row.querySelector('.rate').value || 0); row.querySelector('.amount').textContent = currency.format(amount); total += amount; });
  $('#subtotal').textContent = currency.format(total); $('#grandTotal').textContent = currency.format(total);
}
function setView(view) { if (view === 'settings' && !installed) return; $('#invoiceView').classList.toggle('hidden', view !== 'invoice'); $('#settingsView').classList.toggle('hidden', view !== 'settings'); }
function setSettingsCategory(category) { document.querySelectorAll('.settings-panel').forEach((panel) => panel.classList.toggle('hidden', panel.dataset.category !== category)); $('#settingsCategory').value = category; }
async function hasConnection() { return Boolean(await getSecureSetting('github-repo') && await getSecureSetting('github-branch') && await getSecureSetting('github-token')); }
async function requireConnection() { if (await hasConnection()) return true; alert('Set up and save the Data connection first.'); $('#dataSettings').scrollIntoView({ behavior: 'smooth', block: 'start' }); return false; }
async function saveConnection() { const repo = $('#githubRepo').value.trim(), enteredBranch = $('#githubBranch').value.trim(), enteredToken = $('#githubToken').value.trim(), status = $('#connectionStatus'), previousRepo = await getSecureSetting('github-repo'), previousBranch = await getSecureSetting('github-branch'), token = enteredToken || await readToken(); if (!/^[^/]+\/[^/]+$/.test(repo) || !enteredBranch || !token) { status.textContent = 'Enter a valid repository, branch, and token.'; status.className = 'mt-3 text-sm text-red-700'; return; } if (previousRepo && (previousRepo !== repo || previousBranch !== enteredBranch) && !confirm('Changing the data source can replace the parties, items, logo, and QR currently shown in this app. Continue?')) return; status.textContent = 'Checking data source…'; const headers = { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' }; let source = await fetch(`https://api.github.com/repos/${repo}`, { headers }); if (source.status === 404) { const [owner, name] = repo.split('/'); const user = await fetch('https://api.github.com/user', { headers }); if (!user.ok) { status.textContent = 'Your token could not be verified.'; return; } const account = await user.json(); let canCreate = account.login.toLowerCase() === owner.toLowerCase(); if (!canCreate) { const membership = await fetch(`https://api.github.com/user/memberships/orgs/${owner}`, { headers }); canCreate = membership.ok && (await membership.json()).state === 'active'; } if (!canCreate) { status.textContent = 'This token does not appear to have permission to create a repository for that owner.'; status.className = 'mt-3 text-sm text-red-700'; return; } if (!confirm(`Repository ${repo} does not exist. Create it as a private data repository?`)) return; const endpoint = account.login.toLowerCase() === owner.toLowerCase() ? 'https://api.github.com/user/repos' : `https://api.github.com/orgs/${owner}/repos`; source = await fetch(endpoint, { method: 'POST', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ name, private: true, auto_init: true }) }); if (!source.ok) { status.textContent = (await source.json()).message || 'GitHub denied repository creation.'; status.className = 'mt-3 text-sm text-red-700'; return; } const created = await source.json(); $('#githubBranch').value = created.default_branch; } else if (!source.ok) { status.textContent = 'Could not access that repository.'; status.className = 'mt-3 text-sm text-red-700'; return; } const branch = $('#githubBranch').value.trim(); await setSecureSetting('github-repo', repo); await setSecureSetting('github-branch', branch); if (enteredToken) await saveToken(enteredToken); $('#githubToken').value = ''; $('#tokenHint').textContent = 'A token is saved. Enter a new one only to replace it.'; status.textContent = 'Data source saved.'; status.className = 'mt-3 text-sm text-green-700'; try { await loadData(); } catch {} }

document.addEventListener('click', async (event) => {
  const target = event.target;
  if (target.dataset.view) setView(target.dataset.view);
  if (target.id === 'addLine') addLine();
  if (target.classList.contains('remove-line')) { target.closest('tr').remove(); updateTotals(); }
  if (target.classList.contains('remove-party')) { if (!(await requireConnection())) return; data.parties.splice(+target.dataset.party, 1); saveData(); }
  if (target.classList.contains('remove-item')) { if (!(await requireConnection())) return; data.items.splice(+target.dataset.item, 1); saveData(); }
  if (target.id === 'newInvoice') { $('#partyInput').value = ''; $('#notes').value = ''; $('#lineItems').innerHTML = ''; addLine(); }
  if (target.id === 'printInvoice') window.print();
  if (target.id === 'saveConnection') await saveConnection();
  if (target.id === 'commitParties' || target.id === 'commitItems') { if (await requireConnection()) await commitData(); }
  if (target.id === 'saveLogo') await uploadAsset('logo');
  if (target.id === 'saveQr') await uploadAsset('qr');
});
document.addEventListener('input', (event) => { if (event.target.closest('#lineItems')) updateTotals(); });
document.addEventListener('change', (event) => { if (event.target.classList.contains('item-name')) { const item = data.items.find((x) => x.name === event.target.value); if (item) { event.target.closest('tr').querySelector('.rate').value = item.rate; updateTotals(); } } });
$('#settingsCategory').addEventListener('change', (event) => setSettingsCategory(event.target.value));
$('#partyForm').addEventListener('submit', async (event) => { event.preventDefault(); if (!(await requireConnection())) return; const name = $('#newParty').value.trim(); if (name && !data.parties.includes(name)) { data.parties.push(name); data.parties.sort(); saveData(); } event.target.reset(); });
$('#itemForm').addEventListener('submit', async (event) => { event.preventDefault(); if (!(await requireConnection())) return; const name = $('#newItem').value.trim(), rate = +$('#newRate').value; if (name && !data.items.some((x) => x.name === name)) { data.items.push({ name, rate }); data.items.sort((a,b) => a.name.localeCompare(b.name)); saveData(); } event.target.reset(); });
async function commitData() {
  if (!installed) return; const [repo, branch] = [await getSecureSetting('github-repo'), await getSecureSetting('github-branch')]; const status = $('#commitStatus'); const token = await readToken();
  if (!/^[^/]+\/[^/]+$/.test(repo) || !branch || !token) { status.textContent = 'Enter repository, branch, and token.'; status.className = 'mt-3 text-sm text-red-700'; return; }
  status.textContent = 'Committing…'; status.className = 'mt-3 text-sm text-amber-900';
  try { const url = `https://api.github.com/repos/${repo}/contents/data.json`; const headers = { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' }; const current = await fetch(`${url}?ref=${encodeURIComponent(branch)}`, { headers }); if (!current.ok && current.status !== 404) throw new Error('Could not read data.json. Check repository, branch, and token.'); const file = current.ok ? await current.json() : null; const payload = { message: 'Update invoice data', content: btoa(unescape(encodeURIComponent(JSON.stringify(data, null, 2) + '\n'))), ...(file ? { sha: file.sha } : {}), branch }; const response = await fetch(url, { method: 'PUT', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error((await response.json()).message || 'Commit failed.'); status.textContent = 'Saved and committed. GitHub Pages will reflect it after its next deployment.'; status.className = 'mt-3 text-sm text-green-700'; } catch (error) { status.textContent = error.message; status.className = 'mt-3 text-sm text-red-700'; }
}
async function uploadAsset(kind) { if (!(await requireConnection())) return; const file = $(`#${kind}File`).files[0], status = $('#commitStatus'); if (!file || !file.type.startsWith('image/') || file.size > 2 * 1024 * 1024) { status.textContent = 'Choose an image under 2 MB.'; status.className = 'mt-3 text-sm text-red-700'; return; } status.textContent = `Uploading ${kind}…`; const repo = await getSecureSetting('github-repo'), branch = await getSecureSetting('github-branch'), token = await readToken(); const ext = ({ 'image/png': 'png', 'image/jpeg': 'jpg', 'image/webp': 'webp', 'image/svg+xml': 'svg' })[file.type] || 'png'; const path = `assets/${kind}.${ext}`, url = `https://api.github.com/repos/${repo}/contents/${path}`, headers = { Authorization: `Bearer ${token}`, Accept: 'application/vnd.github+json' }; try { const current = await fetch(`${url}?ref=${encodeURIComponent(branch)}`, { headers }); const existing = current.ok ? await current.json() : null; if (!current.ok && current.status !== 404) throw new Error('Could not access the asset location.'); const bytes = new Uint8Array(await file.arrayBuffer()); let binary = ''; bytes.forEach((byte) => binary += String.fromCharCode(byte)); const response = await fetch(url, { method: 'PUT', headers: { ...headers, 'Content-Type': 'application/json' }, body: JSON.stringify({ message: `Upload invoice ${kind}`, content: btoa(binary), ...(existing ? { sha: existing.sha } : {}), branch }) }); if (!response.ok) throw new Error((await response.json()).message || 'Upload failed.'); data[`${kind}Path`] = path; saveData(); await commitData(); } catch (error) { status.textContent = error.message; status.className = 'mt-3 text-sm text-red-700'; } }
let installPrompt;
window.addEventListener('beforeinstallprompt', (event) => { event.preventDefault(); installPrompt = event; $('#installButton').classList.remove('hidden'); });
$('#installButton').addEventListener('click', async () => { if (!installPrompt) return; installPrompt.prompt(); await installPrompt.userChoice; installPrompt = null; $('#installButton').classList.add('hidden'); });
if (installed) $('#settingsButton').classList.remove('hidden');
if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js');
$('#invoiceDate').value = new Date().toISOString().slice(0, 10);
await loadData(); addLine();
$('#settingsPanels').append($('#dataSettings')); setSettingsCategory('parties');
if (installed) { $('#githubRepo').value = await getSecureSetting('github-repo') || ''; $('#githubBranch').value = await getSecureSetting('github-branch') || 'main'; if (await getSecureSetting('github-token')) $('#tokenHint').textContent = 'A token is saved. Enter a new one only to replace it.'; else { setView('settings'); setSettingsCategory('data'); alert('Set up a data source before managing parties, items, logo, or QR codes.'); } }
